### ISSUE TITLE
Inconsistent variable name (Nov 2020)

### ISSUE THREAD

**Issue by libxx1** [raspberrypilearning/cd-beginner-scratch-sushi#54]
A user raised this feedback showing discrepancy between the step instructions and the image. 

Suite à la création d'une variable "score" on montre une varaible "pointage". Les noms des variables ne sont pas cohérents.

URL: /fr-FR/projects/cd-beginner-scratch-sushi/8

**Comment by libxx1** [comment]
@majamanojlovic can you have a look at this please. I think it's just a case of the image needing to be changed to reflect the name 'score'

**Comment by majamanojlovic** [comment]
@libxx1 will do!
